LEXICON: dict[str, str] = {
    '/start': 'text for the start command',
    '/help': 'text for the help command',
    'other': 'This action does nothingю',
    'admin': 'admin',
    'main_menu_button': 'Main menu 🧨',
    'profile_button': 'Profile 🗃',
    'registration_button': 'Registration 🖋',
    'cancel_button': 'Cancel ❌',
    'info': 'Information about the functionality of the bot:',
    'main': '🌫 Select an action: ',
    'main_kb_placeholder': 'Choose an action...',
    'admin': 'You\'re an admin',
    'click' : 'Click on the button:',
    'github': 'Github repository',
    'aiogram': 'Aiogram documentation',
    'back': 'Come back',
    'nothing_to_cancel': 'There is nothing to cancel. You are outside the state machine.\n\nTo return to registration - /registration',
    'cancel': 'You have exited the state machine.\n\nTo return to registration - /registration',
    'enter_name': 'Enter your name:',
    'incorrect_name': 'You entered an incorrect name. Try again\n\nTo stop filling out the form, enter - /cancel',
    'enter_age': 'Thank you!\n\nNow enter your age:',
    'incorrect_age': 'You entered an incorrect age. Age must be a number between 1 and 100. Try again\n\nTo stop filling out the form, enter - /cancel',
    'enter_sex': 'Thank you!\n\nChoose your gender:',
    'incorrect_age': 'Select gender using buttons. Try again\n\nTo stop filling out the form, enter - /cancel',
    'send_photo': 'Thank you!\n\nSend your photo:',
    'incorrect_photo': 'Send your photo\n\nTo stop filling out the form, enter - /cancel',
    'form_completed': '✅ You have exited the FSM.\nYou have successfully completed the form.\n\nThe profile can be viewed in the profile - /profile',
    'not_registered': 'You have not registered. Registration - /registration',
    'enter_descr': 'Enter your description:',
    'incorrect_descr': 'You entered an incorrect description. Try again\n\nTo stop filling out the form, enter - /cancel',
    }

def get_profile_data(user: dict, message):
  return f'Your profile 🗂\n\n<b>Name:</b> {user[message.from_user.id]["name"]}\n<b>Age:</b> {user[message.from_user.id]["age"]}\n<b>Sex:</b> {user[message.from_user.id]["gender"]}\n<b>Description:</b> {user[message.from_user.id]["description"]}'
