LEXICON: dict[str, str] = {
    "start_message": 'This bot was created for educational purposes and is a template with examples of using various functionality of the aiogram 3 framework for creating telegram bots. 🌿\n\n❓ Bot capabilities - <i>/help</i>\n\n🔗 Source: <a href="https://github.com/BLazzeD21/py-aiogram-template-bot">LINK</a>',
    "help_message": "<b>🤖 Available bot commands</b>\n\n",
    "help_add": "➖ {command} - {description}\n",
    "other": "This action does nothing 👽",
    "admin": "admin",
    "main_menu_button": "Main menu 🧨",
    "profile_button": "Profile 🗃",
    "form_button": "Sign up 🖋",
    "profiles_button": "Profiles 📝",
    "info_button": "Information ℹ️",
    "cancel_button": "Cancel ❌",
    "info_message": "<b>Information about the bot's functions</b>",
    "main": "🌫 Select an action: ",
    "main_kb_placeholder": "Choose an action...",
    "admin": "You're an admin",
    "github": "Github repository",
    "aiogram": "Aiogram documentation",
    "back": "Menu ◀️",
    "back_profiles": "Profiles ◀️",
    "nothing_to_cancel": "There is nothing to cancel. You are outside the state machine.\n\nTo return to registration - <i>/registration</i>",
    "cancel": "You have exited the state machine.\n\nTo return to registration - <i>/registration</i>",
    "registering": "You are registering.\n\nTo stop filling out the form, enter - <i>/cancel</i>",
    "enter_name": "Enter your name:",
    "incorrect_name": "You entered an incorrect name. Try again\n\nTo stop filling out the form, enter - <i>/cancel</i>",
    "enter_age": "Thank you!\n\nNow enter your age:",
    "incorrect_age": "You entered an incorrect age. Age must be a number between 1 and 100. Try again\n\nTo stop filling out the form, enter - <i>/cancel</i>",
    "enter_sex": "Thank you!\n\nChoose your gender:",
    "incorrect_gender": "Select gender using buttons. Try again\n\nTo stop filling out the form, enter - <i>/cancel</i>",
    "send_photo": "Thank you!\n\nSend your photo:",
    "incorrect_photo": "Send your photo\n\nTo stop filling out the form, enter - <i>/cancel</i>",
    "form_completed": "✅ You have exited the FSM.\nYou have successfully completed the form.\n\nThe profile can be viewed in the profile - <i>/profile</i>",
    "not_registered": "You have not registered. Registration - <i>/registration</i>",
    "enter_descr": "Enter your description:",
    "incorrect_descr": "You entered an incorrect description. Try again\n\nTo stop filling out the form, enter - <i>/cancel</i>",
    "select_account": "<b>A list of users 👁</b>",
    "no_users": "No users yet",
    "backward": "◀️ Previous",
    "forward": "Next ➡️",
    "stub": "This is an information button",
    "profile_btn_text": "{username}\'s profile",
    "first_page": "First page 🌕",
    "last_page": "Last page 🌑",
    "male": "Male 🧍🏻‍♂️",
    "female": "Female 🧍🏻‍♀️",
    "not_exist": "This user does not exist 😩", 
    "form_completed_sticker": r'CAACAgIAAxkBAAEoaeRlh49v7tzgcrgszl8qS_ikPiZlEwACUDkAAulVBRg9Q_7QMuwdwDME',
    "get_profile_data": "<b>Profile 🗂</b>\n\n<b>├ ID:</b> <code>{user_id}</code>\n<b>├ Username:</b> @{username}\n<b>├ Name:</b> <code>{name}</code>\n<b>├ Age:</b> <code>{age}</code>\n<b>├ Sex:</b> <code>{gender}</code>\n<b>└ Description:</b> <code>{description}</code>"
}

